[[minigames]]
id = "spleef"

[[minigames]]
id = "bow_spleef"

[[minigames]]
id = "mirror_hop"

[[minigames]]
id = "fine_tuning"

[[minigames]]
id = "treasure_hunter"

[[minigames]]
id = "one_in_the_chamber"

[[minigames]]
id = "anvil_fall"

[[minigames]]
id = "panda_finder"

[[minigames]]
id = "jump_and_run"

[[minigames]]
id = "tnt_run"

[[minigames]]
id = "hot_potato"

[[minigames]]
id = "block_dissolve"

[[minigames]]
id = "cozy_campfire"

[[minigames]]
id = "mining_battle"

[[minigames]]
id = "knockout"

[[minigames]]
id = "musical_minecart"

[[minigames]]
id = "guess_it"

[[minigames]]
id = "pig_race"

[[minigames]]
id = "red_light_green_light"

[[minigames]]
id = "snowball_fight"

[[minigames]]
id = "chicken_shooter"

[[minigames]]
id = "speed_builders"
enabled = false

[[minigames]]
id = "mimicry"

[[minigames]]
id = "splashy_dropper"

[[minigames]]
id = "glowing_bomb"

[[minigames]]
id = "maniac_digger"

[[minigames]]
id = "apocalypse_survival"

[[minigames]]
id = "pillar_battle"

[[minigames]]
id = "aim_master"

[[minigames]]
id = "maze_scape"

[[minigames]]
id = "eggventure"

[[minigames]]
id = "dragon_escape"

[[minigames]]
id = "paintball"

[[minigames]]
id = "dance_floor"
type = [ "kotlin",]

[[minigames]]
id = "killeporter"
type = [ "kotlin",]

