name = "arcade-party-2"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a8e3c7de19670484e79927e019d79317515b9df7439237fa7987ce9373bc099"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
