name = "arcade-party-2"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12291292bbd36592d1655c5d803e5e0c8c3b03f5a1d1ee5c0a71b349cc884eb0"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
